site_name: Playground One
nav:
  - Home: index.md
  - How it Works:
    - Orchestration: how-it-works/orchestration.md
    - Configurations: how-it-works/configurations.md
  - Getting Started:
    - Prepare: getting-started/prepare.md
    - Configuration: getting-started/configuration.md
    - General Life-Cycle: getting-started/life-cycle.md
  - Integrations:
    - Server & Workload Protection: integrations/endpoint-security.md
    # - XDR for Containers: integrations/xdr-for-containers.md
    - Container Security: integrations/container-security.md
    - Prometheus & Grafana: integrations/prometheus-grafana.md
  - Scenarios:
    - EKS:
      - Escape to Host System: scenarios/container-security-eks-escape.md
      - ContainerD Abuse: scenarios/container-security-eks-dind-exploitation.md
      - Runtime Vulnerability Scan: scenarios/container-security-eks-runtime-vulnerability.md
      - Runtime Vulnerability Scan on Fargate: scenarios/container-security-eks-fargate.md
      - Runtime Violations: scenarios/container-security-eks-runtime-violations.md
      - Apache Struts Multipart Encoding Command Injection: scenarios/xdr-for-containers-eks-struts.md
      - Hunger Check: scenarios/hunger-check.md
    - ECS:
      - Apache Struts Multipart Encoding Command Injection: scenarios/v1cs-ecs-struts.md
      - Runtime Vulnerability Scan on ECS: scenarios/v1cs-ecs-runtime-vulnerability.md
      - Tomcat Remote Code Execution: scenarios/xdr-for-containers-ecs-tomcat-rce.md
      - JNDI Injection in HTTP Request: scenarios/xdr-for-containers-ecs-log4j.md
      - Apache Struts Multipart Encoding Command Injection: scenarios/xdr-for-containers-ecs-struts.md
      # - Privileged Shell: scenarios/container-security-eks-privileged-shell.md
    - Artifact Scanning:
      - Scan for Vulnerabilities and Malware: scenarios/tmas-artifact-scanning.md
    # - Server & Workload Protection:
    #   - Malware Upload: scenarios/server-workload-ecs-ec2-malware-upload.md
  - FAQ: faq.md
  - Bloopers: bloopers.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
    - content.code.copy
  favicon: images/playground-icon.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
#   # logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/markus-winkler-785baa34/
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true