site_name: Playground One
nav:
  - Home: index.md
  - Orchestration: orchestration.md
  - Configurations: configurations.md
  - Getting Started:
    - Prepare: getting-started/prepare.md
    - Configuration: getting-started/configuration.md
  - General Life-Cycle: life-cycle.md
  - Integrations:
    - Vision One Endpoint Security: integrations/endpoint_security.md
    - XDR for Containers: integrations/xdr_for_containers.md
    - Sentry: integrations/sentry.md
  - Scenarios:
    - XDR for Containers:
      - Tomcat Remote Code Execution: scenarios/xdr_for_containers-ecs-tomcat-rce.md
      - JNDI Injection in HTTP Request: scenarios/xdr_for_containers-ecs-log4j.md
      - Apache Struts Multipart Encoding Command Injection: scenarios/xdr_for_containers-ecs-struts.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
  # favicon: images/kubecon_logo.jpeg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
#   # logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/cloudnativeca
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true