site_name: Playground One
repo_url: https://github.com/mawinkler/playground-one
nav:
  - Home: index.md
  - How it Works:
    - Orchestration: how-it-works/orchestration.md
    - Configurations:
      - Overview: how-it-works/configurations.md
      - AWS: how-it-works/configurations-aws.md
      - Azure: how-it-works/configurations-azure.md
      - Kind: how-it-works/configurations-kind.md
    - Add-Ons: how-it-works/add-ons.md
  - Getting Started:
    - Prepare: getting-started/prepare.md
    - Configuration: getting-started/configuration.md
    - General Life-Cycle: getting-started/life-cycle.md
  - Integrations:
    - Server & Workload Protection: integrations/endpoint-security.md
    # - XDR for Containers: integrations/xdr-for-containers.md
    - Container Security: integrations/container-security.md
    - Deep Security: integrations/deep-security.md
    - Prometheus & Grafana: integrations/prometheus-grafana.md
    - Splunk: integrations/splunk.md
    - Elastic Stack: integrations/elastic-stack.md
  - Scenarios:
    - Attack Surface Risk Management:
      - Virtual Instance Predictive Attack Path: scenarios/asrm/virtual-machine-attack-path.md
      - IAM User Predictive Attack Path: scenarios/asrm/iam-user-attack-path.md
      - Posture Management:
        - Terraform IaC Scanning with a GitHub Action: scenarios/asrm/pm/template-scanning-terraform-github-action.md
        - CloudFormation IaC Scanning with a GitHub Action: scenarios/asrm/pm/template-scanning-cfn-github-action.md
        - Exception Handling with Pipline Scanning: scenarios/asrm/pm/template-scanning-exception-handling.md
    - XDR Threat Investigation:
      - Automated Observed Attack Techniques Generation: scenarios/xdr/oat-generation.md
      - Automated Workbench Generation: scenarios/xdr/workbench-generation.md
    - Workflow and Automation:
      - Third-Party Integration:
        - Setup Splunk: scenarios/automation/thirdparty/splunk-setup.md
        - Integrate Splunk with Vision One XDR: scenarios/automation/thirdparty/splunk-integrate-vision-one-xdr.md
        - Integrate V1CS Customer Runtime Security Rules with Splunk: scenarios/automation/thirdparty/splunk-integrate-vision-one-custom-rules.md
        - Setup Elastic Stack: scenarios/automation/thirdparty/elastic-stack.md
        - Integrate Elastic Stack with Vision One: scenarios/automation/thirdparty/elastic-stack-vision-one.md
      - Service Gateway:
        - Deploy Service Gateway on AWS Manually: scenarios/automation/service-gateway/v1-aws-service-gateway-manually.md
        - Deploy Service Gateway on AWS Automatically: scenarios/automation/service-gateway/v1-aws-service-gateway-automatically.md
        - Integrate an Active Directory via Service Gateway on AWS: scenarios/automation/service-gateway/v1-integrate-active-directory.md
    - Identity Security:
      - Identity Posture:
        - Populate the Active Directory: scenarios/identity-security/identity-posture/populate-ad.md
    - Endpoint Security:
      - Deep Security:
        - Integrate Deep Security with Vision One: scenarios/endpoint-security/deep-security/ds-integrate.md
        - Integrate Deep Security with Vision One and Service Gateway: scenarios/endpoint-security/deep-security/ds-integrate-and-service-gateway.md
        - Migrate Deep Security to Vision One: scenarios/endpoint-security/deep-security/ds-migrate.md
      - Workload Security:
        - Integrate Workload Security with Vision One: scenarios/endpoint-security/workload-security/ws-integrate.md
        # - Migrate Workload Security to Vision One: scenarios/endpoint-security/workload-security/ws-migrate.md
    - Cloud Security:
      - Container Security:
        - EKS:
          - Escape to Host System: scenarios/cloud-security/container-security/eks/escape.md
          - ContainerD Abuse: scenarios/cloud-security/container-security/eks/dind-exploitation.md
          - Hunger Check: scenarios/cloud-security/container-security/eks/hunger-check.md
          - Runtime Vulnerability Scan: scenarios/cloud-security/container-security/eks/runtime-vulnerability-ec2.md
          - Runtime Vulnerability Scan on Fargate: scenarios/cloud-security/container-security/eks/runtime-vulnerability-fargate.md
          - Integrate V1CS Customer Runtime Security Rules with Splunk: scenarios/automation/thirdparty/splunk-integrate-vision-one-custom-rules.md
        - ECS:
          - Apache Struts Multipart Encoding Command Injection (Runtime Security): scenarios/cloud-security/container-security/ecs/apache-struts-rce.md
          - Runtime Vulnerability Scan: scenarios/cloud-security/container-security/ecs/runtime-vulnerability.md
        # - XDR4C:
        #   - Tomcat Remote Code Execution (XDR for Containers): scenarios/xdr4c/ecs-tomcat-rce.md
        #   - JNDI Injection in HTTP Request (XDR for Containers): scenarios/xdr4c/ecs-log4j.md
        #   - Apache Struts Multipart Encoding Command Injection (XDR for Containers): scenarios/xdr4c/ecs-struts.md
        #   - Apache Struts Multipart Encoding Command Injection: scenarios/xdr4c/eks-struts.md
        - Artifact Scanning:
          - Scan Containers for Vulnerabilities and Malware: scenarios/cloud-security/container-security/artifact-scanning/tmas-artifact-scanning.md
          - Scan Containers with a GitHub Action: scenarios/cloud-security/container-security/artifact-scanning/tmas-github-action.md
      - File Security:
        - Artifact Scanning:
          - Scan Files and Directories for Malware: scenarios/cloud-security/file-security/artifact-scanning//tmfs-artifact-scanning.md
          - Scan S3 Buckets for Malware: scenarios/cloud-security/file-security/artifact-scanning/tmfs-s3-bucket-scanning.md
    # - Privileged Shell: scenarios/container-security-eks-privileged-shell.md
    # - Server & Workload Protection:
    #   - Malware Upload: scenarios/server-workload-ecs-ec2-malware-upload.md
  - FAQ: faq.md
  - Bloopers: bloopers.md
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.tabs.link
    - content.code.copy
    - search.suggest
    - search.highlight
  favicon: images/playground-icon.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
#   # logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/markus-winkler-785baa34/
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true