site_name: Playground One
nav:
  - Home: index.md
  - How it Works:
    - Orchestration: how-it-works/orchestration.md
    - Configurations: how-it-works/configurations.md
    - Versions: how-it-works/versions.md
  - Getting Started:
    - Prepare: getting-started/prepare.md
    - Configuration: getting-started/configuration.md
    - General Life-Cycle: getting-started/life-cycle.md
  - Integrations:
    - Server & Workload Protection: integrations/endpoint-security.md
    # - XDR for Containers: integrations/xdr-for-containers.md
    - Container Security: integrations/container-security.md
    - Deep Security: integrations/deep-security.md
    - Prometheus & Grafana: integrations/prometheus-grafana.md
  - Scenarios:
    - EKS:
      - Escape to Host System: scenarios/eks/escape.md
      - ContainerD Abuse: scenarios/eks/dind-exploitation.md
      - Hunger Check: scenarios/eks/hunger-check.md
      - Runtime Vulnerability Scan: scenarios/eks/runtime-vulnerability-ec2.md
      - Runtime Vulnerability Scan on Fargate: scenarios/eks/runtime-vulnerability-fargate.md
    - ECS:
      - Apache Struts Multipart Encoding Command Injection (Runtime Security): scenarios/ecs/apache-struts-rce.md
      - Runtime Vulnerability Scan: scenarios/ecs/runtime-vulnerability.md
    # - XDR4C:
    #   - Tomcat Remote Code Execution (XDR for Containers): scenarios/xdr4c/ecs-tomcat-rce.md
    #   - JNDI Injection in HTTP Request (XDR for Containers): scenarios/xdr4c/ecs-log4j.md
    #   - Apache Struts Multipart Encoding Command Injection (XDR for Containers): scenarios/xdr4c/ecs-struts.md
    #   - Apache Struts Multipart Encoding Command Injection: scenarios/xdr4c/eks-struts.md
    - Artifact Scanning:
      - Scan Containers for Vulnerabilities and Malware: scenarios/as/tmas-artifact-scanning.md
      - Scan Containers with a GitHub Action: scenarios/as/tmas-github-action.md
      - Scan Files and Directories for Malware: scenarios/as/tmfs-artifact-scanning.md
      - Scan S3 Buckets for Malware: scenarios/as/tmfs-s3-bucket-scanning.md
    # - Privileged Shell: scenarios/container-security-eks-privileged-shell.md
    # - Server & Workload Protection:
    #   - Malware Upload: scenarios/server-workload-ecs-ec2-malware-upload.md
    - Posture Management:
      - Terraform IaC Scanning with a GitHub Action: scenarios/cspm/template-scanning-terraform-github-action.md
      - CloudFormation IaC Scanning with a GitHub Action: scenarios/cspm/template-scanning-cfn-github-action.md
    - Attack Surface Risk Management:
      - Virtual Instance Potential Attack Path: scenarios/asrm/virtual-machine-attack-path.md
      - IAM User Potential Attack Path: scenarios/asrm/iam-user-attack-path.md
    - XDR:
      - Automated Observed Attack Techniques Generation: scenarios/xdr/oat-generation.md
      - Automated Workbench Generation: scenarios/xdr/workbench-generation.md
    - Deep Security:
      - Integrate Deep Security with Vision One: scenarios/ds/ds-integrate.md
      - Migrate Deep Security to Vision One: scenarios/ds/ds-migrate.md
      - Integrate Workload Security with Vision One: scenarios/ds/ws-integrate.md
    #   - Migrate Workload Security to Vision One: scenarios/ds/ws-migrate.md
  - FAQ: faq.md
  - Bloopers: bloopers.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
    - content.code.copy
  favicon: images/playground-icon.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
#   # logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/markus-winkler-785baa34/
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true