apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productapp
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - productapp-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 9000