grafana:
  enabled: false
  service:
    type: ClusterIP

prometheusOperator:
  enabled: true
  service:
    type: ClusterIP
  namespaces:
    releaseNamespace: true
    additional:
    - kube-system
    - trendmicro-system
    - attackers
    - goat
    - victims

prometheus:
  enabled: true
  service:
    type: ClusterIP
