version: "3.7"
services:

  splunk:
    container_name: splunk
    hostname: splunk
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt --gen-and-print-passwd --seed-passwd TrendMicro.1
      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=TrendMicro.1
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - TZ=Europe/Berlin
      - PHP_TZ=Europe/Berlin
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
      - "10701:10701/udp"
      - "10702:10702/udp"
      - "10703:10703/udp"
      - "10704:10704/udp"
      - "10705:10705/udp"
      - "10706:10706/udp"
      - "10707:10707/udp"
    restart: always

# ##########################################################################
# Volumes
# ##########################################################################

volumes:
  opt-splunk-etc:
  opt-splunk-var:
